# Generated by Django 3.2.13 on 2022-06-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='course_desc',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='description',
            new_name='fee_desc',
        ),
    ]
